services:
    voting:
        image: ghcr.io/probableprime/vr-voting-server:latest
        container_name: voting
        pull_policy: always
        network_mode: host
        volumes:
            - ./db:/home/node/app/db:rw
            - ./logs:/home/node/app/logs:rw
        restart: unless-stopped
        ports:
            - 3000:3000
        expose:
            - 3000
    headless:
        container_name: resonite-headless
        pull_policy: always
        network_mode: host
        image: ghcr.io/voxelbonecloud/resonite-headless-docker:main
        env_file: .env
        environment:
            CONFIG_FILE: Config.json
        tty: true
        stdin_open: true
        user: "1000:1000"
        volumes:
            - "./headless/config:/Config:ro"
            - "./headless/logs:/Logs:rw"
        restart: on-failure:5

